"""empty message

Revision ID: 53b8f87bcb30
Revises: cd4da22420c3
Create Date: 2019-12-06 00:23:41.599367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b8f87bcb30'
down_revision = 'cd4da22420c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupName', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groupName')
    )
    op.drop_table('account')
    op.drop_table('group')
    op.add_column('link', sa.Column('acc_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.create_foreign_key(None, 'link', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(None, 'link', 'accounts', ['acc_id'], ['id'])
    op.drop_column('link', 'link_id')
    op.drop_column('link', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('account_id', sa.VARCHAR(length=20), nullable=True))
    op.add_column('link', sa.Column('link_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.drop_constraint(None, 'link', type_='foreignkey')
    op.create_foreign_key(None, 'link', 'group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'link', 'account', ['account_id'], ['id'])
    op.drop_column('link', 'acc_id')
    op.create_table('group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('groupName', sa.VARCHAR(length=30), nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groupName')
    )
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), nullable=True),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('groups')
    op.drop_table('accounts')
    # ### end Alembic commands ###
