"""empty message

Revision ID: cd4da22420c3
Revises: 28f014853e21
Create Date: 2019-12-05 18:29:25.524822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4da22420c3'
down_revision = '28f014853e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('groupName', sa.String(length=30), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('groupName')
    )
    op.create_table('link',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    op.drop_table('group')
    # ### end Alembic commands ###
